# Generated by Django 5.1.4 on 2024-12-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='core.deployment'),
        ),
    ]
